---
  - name: Database Configuration
    hosts: "{{ database_host }}"
    gather_facts: "{{ facts }}"
    become: yes
    vars_files: 
      - ../variables/database_vars.yaml
    tasks:
      - name: Ping 
        ping:

      - name: Install MariaDB and python3-pymysql
        apt: 
          name: "{{ database_packages }}"
          state: latest
          update_cache: yes
      
      - name: Start MariaDB
        systemd:
          name: mariadb
          state: started
      
      #- name: Set Root Password
      #  mysql_user: 
      #    login_unix_socket: /var/run/mysqld/mysqld.sock
      #    login_user: root
      #    login_password: "{{ root_password }}"
      #    name: root
      #    check_implicit_admin: yes
      #    password: "{{ new_root_password }}"
      #    #priv: "*.*:ALL,GRANT"
      #    host: 'localhost'
      
      - name: Create Wordpress Database
        mysql_db:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          login_user: root
          login_password: "{{ new_root_password }}"
          name: "{{ wp_db }}"
          state: present

      - name: Create Wordpress User
        mysql_user:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          login_user: root
          login_password: "{{ new_root_password }}"
          name: "{{wp_user}}"
          password: "{{ wpuser_password }}"
          priv: "{{ wp_db }}.*:ALL"
          state: present

